# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-07 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('tabladetalle', models.TextField()),
                ('pagado', models.BooleanField(default=False)),
                ('importe', models.FloatField()),
                ('fecha', models.DateTimeField(default='01/01/1999 00:00:00')),
                ('nitems', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=30)),
                ('minicodigo', models.CharField(default='', max_length=10)),
                ('codigofabricante', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(default='noimage.jpg', max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=9.99)),
                ('cadenacaracteristicas', models.TextField(default='')),
            ],
        ),
    ]
