# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180316_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=9.99),
        ),
    ]
