# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180407_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default='1999-01-01 00:00:00'),
        ),
    ]
