# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-21 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180321_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cadenaCaracteristicas',
            new_name='cadenacaracteristicas',
        ),
    ]
