# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180407_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='codigo_autorizacion',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='froma_pago',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_tarjeta_habiente',
            field=models.CharField(max_length=201, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_pedido',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_tarjeta',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
