# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='noimage.jpg', max_length=20),
        ),
    ]
