# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-06 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
