# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=10)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
