# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20180405_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='model_pic',
            field=models.ImageField(default='static/images/noimagen.jpg', upload_to='static/images/'),
        ),
    ]
