# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_cliente_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='model_pic',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(default='static/images/noimagen.jpg', upload_to='static/images/'),
        ),
    ]
